server:
  port: 8083

spring:
  application:
    name: auth-microservice

  datasource:
    url: jdbc:mysql://localhost:3306/db_auth?useSSL=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: validate 
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true 
    locations: classpath:db/migration L